*.sink.prometheusServlet.class=org.apache.spark.metrics.sink.PrometheusServlet
master.sink.prometheusServlet.servletPath=/metrics/master/prometheus
worker.sink.prometheusServlet.servletPath=/metrics/prometheus
*.source.jvm.class=org.apache.spark.metrics.source.JvmSource
